table branches_dim
	lineageTag: 63d601cb-1b8f-4819-aeaa-440334d77338

	column 'branch id'
		dataType: string
		lineageTag: 93c59569-ad3c-4a86-b507-309465c64c21
		summarizeBy: none
		sourceColumn: branch id

		annotation SummarizationSetBy = Automatic

	column 'branch name'
		dataType: string
		lineageTag: dc9cf918-210e-4d91-98c3-4ac2f62d3427
		summarizeBy: none
		sourceColumn: branch name

		annotation SummarizationSetBy = Automatic

	partition branches_dim = m
		mode: import
		source =
				let
				    Source = MySQL.Database("localhost", "360_education_db", [ReturnSingleDatabase=true]),
				    #"360_education_db_branches" = Source{[Schema="360_education_db",Item="branches"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(#"360_education_db_branches",{{"branch_id", "branch id"}, {"branch_name", "branch name"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

